# Summary of the feature set.
# Deploy an Openstack environment with OVN configured in the containerized overcloud
composable_scenario: scenario007-multinode-containers.yaml
validate_template: scenario007-multinode.yaml
deployed_server: true

network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false
containerized_overcloud: true

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: false

# This enables the deployment of the overcloud with SSL.
ssl_overcloud: false

# This featureset is extremely resource intensive, so we disable telemetry
# in order to reduce the overall memory footprint
# This is not required in newton
telemetry_args: >-
   {% if release != 'newton' %}
   -e {{ overcloud_templates_path }}/environments/disable-telemetry.yaml
   {% endif %}

# TODO(numans) - Change to neutron-ml2-ovn-ha.yaml once OVN bundle pacemaker support
# is ready.
extra_args: >-
  --ntp-server pool.ntp.org
  {% if release in ['pike', 'queens'] -%}
  -e {{ overcloud_templates_path }}/environments/services-docker/neutron-ovn.yaml
  {%- else -%}
  -e {{ overcloud_templates_path }}/environments/services/neutron-ovn.yaml
  {%- endif -%}

# If `run_tempest` is `true`, run tempests tests, otherwise do not
# run them.
tempest_config: true
test_ping: false
run_tempest: true
test_regex: ''
tempest_whitelist:
  - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops'

deployed_server: >-
  {% if release in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
deploy_steps_ansible_workflow: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
config_download_args: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  -e /usr/share/openstack-tripleo-heat-templates/environments/config-download-environment.yaml
  -e {{ working_dir }}/config-download.yaml
  --config-download
  --deployed-server
  --disable-validations
  --verbose
  {%- endif -%}
