undercloud_generate_service_certificate: false

# This enables the run of several tripleo-validations tests through Mistral
run_tripleo_validations: True
# This enables the run of tripleo-validations negative tests through shell
# scripts
run_tripleo_validations_negative_tests: True
# Exit tripleo-quickstart on validations failure
exit_on_validations_failure: False

# pacemaker settings are configured in the scenario template
# do not set `enable_pacemaker` in the featureset

deployed_server: true
composable_scenario: scenario004-multinode.yaml
validate_template: scenario004-multinode.yaml
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

# Tempest configuration, keep always at the end of the file
# Use the traditional ping test in newton and ocata
# Run tempest in pike+

test_ping: >-
  {% if release in ['newton', 'ocata'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

run_tempest: >-
  {% if release in ['newton', 'ocata'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

# Run tempest in containers when at least undercloud is containerized
tempest_format: >-
  {% if containerized_undercloud|bool -%}
  container
  {%- else -%}
  packages
  {%- endif -%}

test_white_regex: ''
tempest_whitelist_old:
  - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops'
tempest_whitelist_new:
  - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops'
  - 'manila_tempest_tests.tests.api.test_shares.SharesCephFSTest.test_create_get_delete_share'

# manila test is disabled in older releases as a temporary workaround for
# https://launchpad.net/bugs/1790857
tempest_whitelist: >-
  {% if release not in ['newton', 'ocata', 'pike'] -%}{{ tempest_whitelist_new }}
  {%- else -%}{{ tempest_whitelist_old }}
  {%- endif -%}

tempest_extra_config: >
  {
    {% if release in ['newton', 'ocata', 'pike', 'queens'] -%}
    'object-storage-feature-enabled.discoverability': 'False',
    'service_available.swift': 'False',
    {%- endif -%}
    {% if release in ['queens'] -%}
    'share.max_api_microversion': '2.42',
    {%- endif -%}
    {% if release in ['pike'] -%}
    'share.max_api_microversion': '2.40',
    {%- endif -%}
    {% if release in ['ocata'] -%}
    'share.max_api_microversion': '2.32',
    {%- endif -%}
    {% if release in ['newton'] -%}
    'share.max_api_microversion': '2.22',
    {%- endif -%}
    'share.multitenancy_enabled': 'False',
    'share.enable_protocols': 'cephfs',
    'share.capability_snapshot_support': 'False',
    'share.capability_create_share_from_snapshot_support': 'False',
  }

tempest_plugins:
  - python2-manila-tests-tempest
