undercloud_generate_service_certificate: false

# This enables the run of several tripleo-validations tests through Mistral
run_tripleo_validations: True
# This enables the run of tripleo-validations negative tests through shell
# scripts
run_tripleo_validations_negative_tests: True
# Exit tripleo-quickstart on validations failure
exit_on_validations_failure: False

# pacemaker settings are configured in the scenario template
# do not set `enable_pacemaker` in the featureset

deployed_server: true
composable_scenario: scenario004-multinode.yaml
validate_template: scenario004-multinode.yaml
composable_roles: true
overcloud_roles:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
    networks:
      - External
      - InternalApi
      - Storage
      - StorageMgmt
      - Tenant

# Tempest configuration, keep always at the end of the file
# Use the traditional ping test in newton and ocata
# Run tempest in pike+

test_ping: >-
  {% if release in ['newton', 'ocata'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}

run_tempest: >-
  {% if release in ['newton', 'ocata'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}

# Run tempest in containers when at least undercloud is containerized
tempest_format: >-
  {% if containerized_undercloud|bool -%}
  container
  {%- else -%}
  packages
  {%- endif -%}

test_white_regex: ''
tempest_whitelist:
  - 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops'
tempest_extra_config: >-
  {% if release not in ['newton', 'ocata', 'pike', 'queens'] -%}
    {}
  {%- else -%}
    {'object-storage-feature-enabled.discoverability': 'False', 'service_available.swift': 'False'}
  {%- endif -%}
