undercloud_generate_service_certificate: false
ssl_overcloud: false
undercloud_check_idempotency: true
undercloud_check_sanity: false

test_ping: false
run_tempest: true
test_regex: ''
tempest_undercloud: true
tempest_overcloud: false
# Basic set of tempest tests to validate undercloud
tempest_whitelist:
  - 'tempest.api.identity'
  - 'tempest.api.image.v2.test_images.BasicOperationsImagesTest'
  - 'tempest.api.image.v2.test_images_tags_negative.ImagesTagsNegativeTest'
  - 'tempest.api.image.v2.test_images_member_negative.ImagesMemberNegativeTest'
  - 'tempest.api.compute.admin.test_flavors'
  - 'tempest.api.compute.flavors'
  - 'tempest.api.compute.keypairs'
  - 'tempest.api.compute.admin.test_quotas'
  - 'tempest.api.compute.admin.test_aggregates_negative'
  - 'tempest.api.compute.security_groups'
  - 'tempest.api.network.test_networks'
  - 'tempest.api.network.test_networks_negative'
  - 'tempest.api.network.test_security_groups_negative'
  - 'tempest.api.network.test_ports'
  - 'tempest.api.network.test_routers_negative'
