# Define a single controller node
overcloud_nodes:
  - name: control_0
    flavor: control
    default_name: overcloud-controller-0
    hostnamemap_override: "{{ hostvars[groups['overcloud'][0]].ansible_hostname }}"

node_count: 1

deployed_server_overcloud_roles:
  - name: Controller
    hosts: "{{ subnodes.0 }}"

topology: >-
  --compute-scale 0

