---
- name: Destroy previous setup
  hosts: virthost
  gather_facts: yes
  vars:
    - libvirt_volume_path: /opt/vm_images
    - libvirt_volume_pool: oooq_pool
    - libvirt_uri: qemu:///system
    - working_dir: /tmp/
    - overcloud_nodes:
      - name: subnode-0
        flavor: control

      - name: subnode-1
        flavor: control
  roles:
    - libvirt/teardown/nodes
  become: true

- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: virthost
  gather_facts: yes
  vars:
    - pub_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
    - libvirt_volume_path: /opt/vm_images
    - image_fetch_dir: "{{ local_working_dir }}"
    - fake_nodepool_vms: true
    - create_instackenv_json: false
    - libvirt_uri: qemu:///system
    - vm_pass: random
    - control_vcpu: 6
    - control_memory: 16384
    - overcloud_nodes:
      - name: subnode-0
        flavor: control

      - name: subnode-1
        flavor: control
    - images:
      - name: centos
        url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1701.qcow2
        type: qcow2
        md5sum: "bc62ad193b085680952edfa7face0f23 *CentOS-7-x86_64-GenericCloud-1701.qcow2"

  roles:
    - libvirt/setup/overcloud
  become: true

- name: Add nodes to the generated inventory
  hosts: localhost
  gather_facts: yes
  roles:
    - tripleo-inventory

